config/routes.rb
CreativeArt::Application.routes.draw do
  root to: 'static_pages#home'

  match "/help",    to: 'static_pages#help'
  match "/about",   to: "static_pages#about"
  match "/contact", to: "static_pages#contact"
  match "/calendar", to: "static_pages#calendar"

  resources :courses

  resources :teachers
  resources :sessions, only: [:new, :create, :destroy]

  match '/teachers_signin',  to: 'sessions#new'
  match '/teachers_signout', to: 'sessions#destroy', via: :delete

end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id              :integer         not null, primary key
#  teacher_name    :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  username        :string(255)
#  remember_token  :string(255)
#  admin           :boolean         default(FALSE)
#

class Teacher < ActiveRecord::Base
  attr_accessible :username, :teacher_name, :password, :password_confirmation
  attr_reader :created_at
  has_secure_password

  before_save { self.username.downcase! }
  before_save { self.teacher_name.downcase! }
  before_save :create_remember_token

  validates :username, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :teacher_name, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :create



  def to_param
    "#{self.id}-#{(self.teacher_name).gsub(/\s+/, "-")}"
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :signed_in_teacher
  before_filter :correct_teacher, only: [:edit, :update]
  before_filter :admin_teacher, only: [:destroy, :new, :edit]

  def index
    @teachers = Teacher.paginate(page: params[:page], order: 'teacher_name')
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(params[:teacher])
    if @teacher.save
      teacher_sign_in @teacher
      flash[:success] = "Welcoming The New Teacher"
      redirect_to @teacher
    else
      render 'new'
    end
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    @teacher = Teacher.find(params[:id])
    if @teacher.update_attributes(params[:teacher])
      flash[:success] = "Profile updated"
      if !current_teacher.admin?
        teacher_sign_in @teacher
      end
      redirect_to @teacher
    else
      render 'edit'
    end
  end

  def destroy
    Teacher.find(params[:id]).destroy
    flash[:success] = "Teacher destroyed."
    redirect_to teachers_path
  end

  private

    def signed_in_teacher
      unless teacher_signed_in?
        store_location
        redirect_to teachers_signin_path, notice: "Please sign in."
      end
    end

    def correct_teacher
      @teacher = Teacher.find(params[:id])
      redirect_to(root_path) unless current_teacher?(@teacher) || current_teacher.admin?
    end

    def admin_teacher
      if !current_teacher.admin?
        redirect_to teachers_path
      end
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_main_header.html.erb
<header "nav-logo">
      <div class = 'logo_container'>
        <%= link_to image_tag("creative.jpg", :alt => "Creative Art and Drawing Studio", :id => "logo"), root_path, id: "logo_button" %>
      <div>
      <nav class = 'login_bar'>
        <ul>
          <% if teacher_signed_in? %>
            <li><%= link_to "Teachers", teachers_path %></li>
            <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">My Stuff</a>
              <ul>
                <li><%= link_to "My page", current_teacher %></li>
                <% if current_teacher.admin? %>
                <li><%= link_to "Settings", edit_teacher_path(current_teacher) %></li>
                <% end %>
              </ul>
            </li>
            <li>
              <%= link_to "Sign out", teachers_signout_path, method: "delete" %>
            </li>
          <% end %>
        </ul>
      </nav>
</header>

app/views/teachers/_teacher.html.erb
<li>
  <%= link_to teacher.teacher_name, teacher %>
  <% if current_teacher.admin? && !current_teacher?(teacher) %>
     | <%= link_to "edit", edit_teacher_path(teacher) %>
     | <%= link_to "delete", teacher, method: :delete,
                                     data: { confirm: "You sure?"} %>
  <% end %>
</li>

app/views/teachers/edit.html.erb
<%= provide(:title, "Edit teacher") %>
<%= render 'teachers/main_header' %>
<nav id='login_bar'>
  <h1>Update teacher information</h1>
</nav>
<section id='main'>
  <div class="row">
    <%= form_for @teacher do |f| %>

      <%= render 'shared/error_messages'%>

      <%= f.label :username, "Login Name" %>
      <%= f.text_field :username %><br />

      <%= f.label :teacher_name, "Full Name" %>
      <%= f.text_field :teacher_name %><br />

      <%= f.label :password %>
      <%= f.password_field :password %><br />

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "create_button" %>

    <% end %>
  </div>
</section>

app/views/teachers/index.html.erb
<% provide(:title, 'All Teachers') %>
<%= render 'teachers/main_header' %>
<nav id='login_bar'>
  <h1>All Teachers</h1>
  <% if teacher_signed_in? %>
    <% if current_teacher.admin? %>
      <%= link_to 'Add A New Teacher', new_teacher_path, :class=>'new' %>
    <% end %>
  <% end %>
</nav>
<section id='main'>

    <%= will_paginate %>

    <ul class="teachers">
          <%= render @teachers %>
    </ul>

    <%= will_paginate %>

</section>

app/views/teachers/new.html.erb
<% provide(:title, "New Teacher") %>
<%= render 'teachers/main_header' %>
<nav id='login_bar'>
  <h1>Add A New Teacher</h1>
</nav>
<section id='main'>
  <div class="row">
    <%= form_for @teacher do |f| %>

      <%= render 'shared/error_messages'%>

      <%= f.label :username, "Login Name" %>
      <%= f.text_field :username %><br />

      <%= f.label :teacher_name, "Full Name" %>
      <%= f.text_field :teacher_name %><br />

      <%= f.label :password %>
      <%= f.password_field :password %><br />

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create Teacher", class: "create_button" %>

    <% end %>
  </div>
</section>

app/views/teachers/show.html.erb
<% provide(:title, @teacher.teacher_name.titleize) %>
<%= render 'teachers/main_header' %>
<nav id='login_bar'>
  <h1><%= @teacher.teacher_name.titleize %></h1>
  <% if teacher_signed_in? %>
    <% if current_teacher.admin? %>
      <%= link_to 'Edit Teacher', edit_teacher_path(@teacher), :class=>'new' %>
    <% end %>
  <% end %>
</nav>
<section id='main'>
  <section class="main-body">
    <h2>
        Future Show teacher Page for <a href='http://creative-studios.herokuapp.com'>Creative Art and Drawing Studio</a>  website. We do appreciate your patients.
      </h2>
  </section>
</section>